GET http://localhost:4000/blogpool

###

GET http://localhost:3000/blogpool/4

###

POST http://localhost:3000/blogpool
Content-Type: application/json

{
    "login": "amazing",
    "email": "subscribe@gmail.com",
    "password": "azerty",
    "type": true
}